name = "swarlipi-secure-sync"
main = "src/index.ts"
compatibility_date = "2026-08-22"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "https://edu6tron.github.io"
GITHUB_APP_CLIENT_ID = "Iv23li7xRW1HbwedSG4u"
